# Ledger Application Configuration - Example
# Copy this file to config.toml and modify as needed

[database]
# Database type to use
# Options: "in_memory", "postgres", "mongodb"
type = "in_memory"

# PostgreSQL configuration (uncomment when type = "postgres")
# [database.postgres]
# host = "localhost"
# port = 5432
# database = "ledger"
# user = "ledger_user"
# password = "your_password_here"

# MongoDB configuration (uncomment when type = "mongodb")
# [database.mongodb]
# uri = "mongodb://localhost:27017"
# database = "ledger"
